### ISSUE TITLE
Cleanup the sphere intersection function

### ISSUE THREAD

**Issue by Carlbaum** [novalain/gi-ray#95]
if (t0 < 0) {
  t0 = t1;
}
if (t0 < 0) {
  return nullptr;
}

if t0 is actually less than 0 we check it twice.. should probably be something like:
if (t0 < 0) {
  if (t1 < 0) {
    return nullptr;
  }
  t0 = t1;
}

**Comment by novalain** [comment]
Yeeee this is a mess. Compare and maybe go back to the old sphere intersection method
